# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: agarcia2 <agarcia2@student.42barcelona.co  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/29 13:05:40 by agarcia2          #+#    #+#              #
#    Updated: 2025/11/29 13:19:38 by agarcia2         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NMAE		=	push_swap\
CC		=	cc
CFLAGS		=	-Wall -Werror -Wextra
ASANFLAGS	=	-g3 -fsanitize=undefined,address

